In [1]:
import numpy as np

# Array

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


## Creating Array

In [3]:
print(np.array.__doc__)

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If obj

In [4]:
a = np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [6]:
np.array(['test', 'string'])

array(['test', 'string'], dtype='<U6')

In [7]:
np.array([[1,2], [3,2], [4,5]])

array([[1, 2],
       [3, 2],
       [4, 5]])

In [8]:
np.array([[1,2,3], [5,3,2]], dtype=float)

array([[1., 2., 3.],
       [5., 3., 2.]])

In [9]:
print(np.zeros.__doc__)

zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.20.0

    Returns
    -------
    out

In [10]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
print(np.ones.__doc__)


    Return a new array of given shape and type, filled with ones.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.20.0

    Returns
    -------
    out : ndarray
        Array of ones with the given sha

In [13]:
dim = (3,3)
np.ones(dim)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
print(np.empty.__doc__)

empty(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, without initializing entries.

    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.20.0

    Returns
    --

In [15]:
np.empty(5)

array([2.12199579e-314, 4.67296746e-307, 3.89323729e-321, 3.79442416e-321,
       1.67640452e-312])

In [16]:
print(np.arange.__doc__)

arange([start,] stop[, step,], dtype=None, *, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warning sections below for more information.

    Parameters
    ----------
    star

In [17]:
print(np.arange(4))
print(np.arange(1, 5, 2)) #(start, end, step)

[0 1 2 3]
[1 3]


In [18]:
np.arange(0, 5, .5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [19]:
np.array([1,2])
np.zeros(6)
np.zeros((4,5))
np.ones(5)
np.empty(5)
np.arange(3, 20, 4)

array([ 3,  7, 11, 15, 19])

## Add, Remove, and Sort

In [20]:
# Append
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
arr = np.append(arr, [1,2])

In [22]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [23]:
# Delete
arr = np.delete(arr, -1)

In [24]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 1])

In [25]:
# Sort
arr2 = np.array([2,5,6,3,8,7,1])
arr2

array([2, 5, 6, 3, 8, 7, 1])

In [26]:
np.sort(arr2)

array([1, 2, 3, 5, 6, 7, 8])

## Shape and Size

In [27]:
arr = np.array([
    np.arange(3),
    np.arange(3,6),
    np.arange(6,9)
])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
# ndim
arr.ndim

2

In [29]:
array_example = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        np.arange(9,13)
    ],
    [
        np.arange(13,17),
        np.arange(17,21),
        np.arange(21,25)
    ]
])

In [30]:
array_example

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [31]:
array_example.ndim

3

In [32]:
print(array_example)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [33]:
print(arr.size)
print(array_example.size)

9
24


In [34]:
print(arr.shape)
print(array_example.shape)

(3, 3)
(2, 3, 4)


In [35]:
arr_one = np.array([np.arange(1,6)])
arr_one

array([[1, 2, 3, 4, 5]])

In [36]:
print('Dimension :', arr_one.ndim)
print('Size :', arr_one.size)
print('Shape :', arr_one.shape)

Dimension : 2
Size : 5
Shape : (1, 5)


In [37]:
## Reshape

In [38]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [39]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [40]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [41]:
a.reshape(3,2,1)

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [42]:
print(np.reshape.__doc__)


    Gives a new shape to an array without changing its data.

    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        changing fastest, and the last index changing slowest. Note that
        the 'C

## Convert 1D to 2D

np.newaxis

In [43]:
a = np.arange(1,7)
a.shape

(6,)

In [44]:
a.reshape(1,6).shape

(1, 6)

In [45]:
a2 = a[np.newaxis]
print("Shape :", a2.shape)
print("Array :", a2)

Shape : (1, 6)
Array : [[1 2 3 4 5 6]]


In [46]:
row_vector = a[np.newaxis, :]
print("Shape :", row_vector.shape)
print("Array :", row_vector)

Shape : (1, 6)
Array : [[1 2 3 4 5 6]]


In [47]:
col_vector = a[:, np.newaxis]
print("Shape :", col_vector.shape)
print("Array :", col_vector)

Shape : (6, 1)
Array : [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


np.expand_dims

In [48]:
print("Shape :", a.shape)
print("Array :", a)

Shape : (6,)
Array : [1 2 3 4 5 6]


In [49]:
b = np.expand_dims(a, axis=1)
print("Shape :", b.shape)
print("Array :", b)

Shape : (6, 1)
Array : [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [50]:
c = np.expand_dims(a, axis=0)
print("Shape :", c.shape)
print("Array :", c)

Shape : (1, 6)
Array : [[1 2 3 4 5 6]]


## Indexing and Slicing

In [51]:
data = np.arange(1,6)

In [52]:
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3 4 5]
1
2
[1 2]
[2 3 4 5]
[4 5]


In [53]:
data = np.array([
    np.arange(1,5),
    np.arange(5,9),
    np.arange(9,13)
])
print("Shape :", data.shape)
print("Array : \n", data)

Shape : (3, 4)
Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [54]:
print(data[data>=5])

[ 5  6  7  8  9 10 11 12]


In [55]:
five_up = (data >= 5)

print(data[five_up])
print(data[data >= 5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [56]:
divisible_by_2 = (data % 2 == 0)

In [57]:
print(data[divisible_by_2])

[ 2  4  6  8 10 12]


In [58]:
data_2 = data[(data > 2) & (data < 11)]
print(data_2)

[ 3  4  5  6  7  8  9 10]


## Creating Array from existing data

In [59]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr2 = arr[2:7]
arr2

array([3, 4, 5, 6, 7])

### Stack

In [61]:
a_1 = np.array([
    [1,1],
    [2,2]
])
a_2 = np.array([
    [3,3],
    [4,4]
])

In [62]:
np.vstack((a_1,a_2,a_1))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [1, 1],
       [2, 2]])

In [63]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

### Split

In [64]:
arrSplit = np.array([
    np.arange(1, 13),
    np.arange(13, 25)
])
arrSplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [65]:
arrSplit.shape

(2, 12)

In [66]:
np.hsplit(arrSplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [67]:
np.vsplit(arrSplit, 2)[0]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

### Copy and View

In [68]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [69]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
a[0,0] = 10
a

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
b

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic Array Operation

In [74]:
a = np.array([1,2,3,4])

In [75]:
a.sum()

10

In [76]:
b = np.array([
    [1,1],
    [2,2]
])

In [77]:
b

array([[1, 1],
       [2, 2]])

In [78]:
b.sum(axis=0)

array([3, 3])

In [79]:
b.sum(axis=1)

array([2, 4])

In [80]:
b.sum()

6

In [81]:
data = np.array([1,2])
data

array([1, 2])

In [82]:
ones = np.ones(2)
ones

array([1., 1.])

In [83]:
data + ones

array([2., 3.])

In [84]:
data * data

array([1, 4])

In [85]:
data /data

array([1., 1.])

### Broadcasting

In [86]:
data + 10

array([11, 12])

In [87]:
data * 10

array([10, 20])

In [88]:
array_example.max()

24

In [89]:
array_example.min()

1

In [90]:
array_example.sum()

300

In [91]:
array_example

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [92]:
A = np.array([[0.45, 0.17, 0.34, 0.55],
              [0.54, 0.051, 0.40, 0.556],
              [0.127, 0.824, 0.265, 0.569]])

In [93]:
A

array([[0.45 , 0.17 , 0.34 , 0.55 ],
       [0.54 , 0.051, 0.4  , 0.556],
       [0.127, 0.824, 0.265, 0.569]])

In [94]:
A.min(axis=1)

array([0.17 , 0.051, 0.127])

In [95]:
A.max(axis=0)

array([0.54 , 0.824, 0.4  , 0.569])

## Matrices

In [96]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [97]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [98]:
np.random.random((3,2))

array([[0.81616927, 0.34924354],
       [0.03313205, 0.77655222],
       [0.07180549, 0.10338075]])

In [99]:
data = np.array([[1,2], [3,4]])
data

array([[1, 2],
       [3, 4]])

In [100]:
one = np.ones((2,2))
one

array([[1., 1.],
       [1., 1.]])

In [101]:
print(data + one)

[[2. 3.]
 [4. 5.]]


In [102]:
one_row = np.ones((1,2))
one_row

array([[1., 1.]])

In [103]:
print(data + one_row)

[[2. 3.]
 [4. 5.]]


In [104]:
b = np.array([1,2])

In [105]:
print(data + b)

[[2 4]
 [4 6]]


In [106]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [107]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [108]:
np.dot(a_1, a_2).shape

(2, 2)

In [109]:
data = np.array([[1,2], [3,4], [5,6]])

In [110]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [111]:
print(data[0])

[1 2]


In [112]:
print(data[0,1])

2


In [113]:
print(data[2,0])

5


In [114]:
print(data[1:])

[[3 4]
 [5 6]]


In [115]:
print(data[:, 1])

[2 4 6]


 ### Matrix Agregation

In [116]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [117]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [118]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


### Transposing and Reshaping

In [119]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [120]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [121]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [122]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [124]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [125]:
ndarr = np.array([
    [
        [1,2],
        [3,4]
    ],[
        [5,6],
        [7,8]
    ]
])

In [126]:
ndarr.shape

(2, 2, 2)

In [127]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [128]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [129]:
print(np.random.random((4,3,2)))

[[[0.62130961 0.64898361]
  [0.60097666 0.54558939]
  [0.85625315 0.29134092]]

 [[0.64304617 0.10039372]
  [0.35195688 0.10105329]
  [0.03575758 0.41790103]]

 [[0.36889234 0.74366695]
  [0.40248295 0.06150102]
  [0.39304626 0.75798512]]

 [[0.46723761 0.54123114]
  [0.3992194  0.04849288]
  [0.3105768  0.35319403]]]


### Flatten N-Dimensional Array

In [130]:
arr = np.random.random((4,3,2))

In [131]:
arr.ndim

3

In [132]:
arr_flatten = arr.flatten()
arr_flatten.ndim

1

In [133]:
arr_ravel = arr.ravel()
arr_ravel.ndim

1

In [134]:
np.random.random(5)

array([0.42782237, 0.19371568, 0.30671776, 0.33634451, 0.7769899 ])

In [135]:
np.random.random((5,5))

array([[0.84141093, 0.87683917, 0.08478896, 0.99066722, 0.70286778],
       [0.35109757, 0.48946651, 0.47933942, 0.77027696, 0.69124949],
       [0.23318811, 0.74849652, 0.278626  , 0.93986938, 0.28124298],
       [0.40316652, 0.85184489, 0.4013382 , 0.61870516, 0.11108805],
       [0.16151022, 0.06286063, 0.01731064, 0.22132995, 0.51624407]])

In [136]:
arr = np.arange(1, 100, 3)

In [137]:
print(arr.max())

97


In [138]:
arr.mean()

49.0

In [139]:
np.median(arr)

49.0

In [140]:
np.log(arr)

array([0.        , 1.38629436, 1.94591015, 2.30258509, 2.56494936,
       2.77258872, 2.94443898, 3.09104245, 3.21887582, 3.33220451,
       3.4339872 , 3.52636052, 3.61091791, 3.68887945, 3.76120012,
       3.8286414 , 3.8918203 , 3.95124372, 4.00733319, 4.06044301,
       4.11087386, 4.15888308, 4.20469262, 4.24849524, 4.29045944,
       4.33073334, 4.36944785, 4.40671925, 4.44265126, 4.47733681,
       4.51085951, 4.54329478, 4.57471098])

In [141]:
arr2 = np.random.random((5,5))

In [142]:
range_arr2 = arr2.max() - arr2.min()

In [143]:
range_arr2

0.9145033239686244